### ISSUE TITLE
This is the 

### ISSUE THREAD

**Issue by Jargon57** [5tephano/Easy_PY_to_EXE#1]
It tells me that the python 34.dll has some sort of problem with my version of python(3.5)
I bet you are tiered of answering noobs like me but what do I do?
I made this comment on your youtube channel and you told me to take a 
screenshot.

![untitled](https://cloud.githubusercontent.com/assets/21182129/17869941/51a6f82a-68ad-11e6-8b43-69a21590d8ff.png)`
My apologies for how small it it

**Comment by Jargon57** [comment]
also, grat

**Comment by 5tephano** [comment]
When reviewing this I'd say the Cx_Freeze component is not working correctly/ as intended. 
What you can do: 
a) Switch Python Versions to 3.4 (Wouldn't affect much, but you would need to reinstall pygame)
b) Wait for me to put out the resource patch. 

I will have the resource patch out within a few hours to fix this exact problem. Thank you for posting this screenshot and I will absolve the issue shortly.

**Comment by 5tephano** [comment]
Looking into Cx_Freeze doesn't support Python 3.5 at this current time. I am looking into making the program work as a GUI for other Exe makers if Cx_Freeze fails. 

This adds more time needed though -_-

**Comment by Jargon57** [comment]
So should I re-install pygame, re-write (or just copy and paste) my program on Python 3.4 and then run your program?

**Comment by Jargon57** [comment]
So downgraded to Python 3.4 and now it tells me that
'Python is not recognised as an internal or external command'

**Comment by 5tephano** [comment]
http://stephanoyoutube.weebly.com/easy-py-to-exe.html#bug

**Comment by 5tephano** [comment]
That I can readily and quickly fix.

**Comment by 5tephano** [comment]
Youll have to go through the steps on the right side. On the bright side it only has to be done once.

**Comment by Jargon57** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21182129/17934205/f6ca6d20-6a0e-11e6-9a49-239464b1b5e1.png)
Now even though my file is spelt correctly, and my directory is correct and it isn't even a `pyw` file, it still gives this error.

Thanks for spending all of this time on me :)

**Comment by 5tephano** [comment]
A GUI program is for pyw files. CONSOLE is if you have the console window open behind it, so a .py file. 
Also try adding a forward slash after the assets folder. If that doesn't work keep execution path as it is.

**Comment by Jargon57** [comment]
WHOO HOO! IT WORKS!! THANKS SOO MUCH MATE! IV'E BEEN TRYING FOR NEARLY A MONTH NOW TO GET THIS TO WORK!! GOD BLESS YOU MAN!!
:) :)
:)
:)
:)
:)
:)
`print ("You are an epic booss!")`

**Comment by Jargon57** [comment]
You certainly earned a subscriber

**Comment by 5tephano** [comment]
Thank you :)
